[package]
name = "off-chain-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hex = "0.4.3"
hmac = "0.12.1"
sha2 = "0.10.8"

axum = { version = "0.6.20", features = ["macros"] }
bb8 = "0.8.2"
bb8-redis = "0.15.0"
candid = "0.10.6"
chrono = { version = "0.4.34", features = ["serde"] }
futures = "0.3.30"
ic-agent = "0.33.0"
rust-s3 = { version = "0.33.0", features = [
    "tokio-rustls-tls",
], default-features = false }
# redis = { version = "0.23.0", features = ["tls-native-tls"] }
redis = { version = "0.25.2", features = [
    "tokio-rustls-comp",
    "aio",
    "connection-manager",
] }
serde = "1.0.197"
serde_bytes = "0.11.14"
serde_json = "1.0.114"
stringreader = "0.1.1"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "time"] }
indicatif = { version = "0.17.8", features = ["futures"] }
tonic = { version = "0.11.0", features = ["tls-roots"] }
prost = "0.12.4"
tower = { version = "0.4", features = ["full"] }
hyper = { version = "0.14.26", features = ["full"] }
http = "0.2.11"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
headers = "0.4.0"
tonic-reflection = "0.11.0"
reqwest = { version = "0.12.3", features = [
    "json",
    "rustls-tls",
], default-features = false }
once_cell = "1.19.0"
yup-oauth2 = { version = "8.3.3", features = ["hyper-rustls"] }
tonic-web = "0.11.0"
log = "0.4.21"
yral-metadata-client = { git = "https://github.com/go-bazzinga/yral-metadata.git", features = [
    "rustls-tls",
], default-features = false }
config = { version = "0.14.0", features = ["toml"] }
serde_with = "3.7.0"
thiserror = "1.0.58"
env_logger = "0.11.3"
anyhow = "1.0.86"
# yral-metadata-types = { git = "https://github.com/go-bazzinga/yral-metadata", rev = "c2c5d254ac273681a66966d62b6f01785679a1be", default-features = false }


[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
candid_parser = "0.1.1"
serde_json = "1.0.110"
convert_case = "0.6.0"
tonic-build = "0.11"

[[bin]]
name = "icp-off-chain-agent"
path = "src/main.rs"
